/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DemiGod1410 (https://sketchfab.com/DemiGod1410)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/figma-5a66a770e9864e50870e5d5f17c4b211
Title: Figma
*/

import React, { useRef } from 'react';
import { Float, useGLTF } from '@react-three/drei';

const FigmaLogo = (props) => {
  const { nodes, materials } = useGLTF('models/figma.glb');
  return (
    <Float FloatIntensity={1}>
      <group position={[8, 8, 0]} scale={3} {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.figma_Texture_0.geometry}
          material={materials.Texture}
          position={[-2.6, 0.2, 1.824]}
          rotation={[-Math.PI / -17, 0, 0.2]}
          scale={0.1}
        />
      </group>
    </Float>
  );
};

useGLTF.preload('models/figma.glb');

export default FigmaLogo;
