/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: sudo-self (https://sketchfab.com/sudo-self)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/github-b2bd1d8290e44ce49e7e41dd495592b5
Title: GitHub
*/

import React from 'react';
import { Float, useGLTF } from '@react-three/drei';

const GithubLogo = (props) => {
  const { nodes } = useGLTF('./models/github.glb');

  return (
    <Float floatIntensity={5} rotationIntensity={0}>
      <group position={[8, 8, 0]} scale={3} {...props}>
        <group rotation={[-0.1, Math.PI / 5, Math.PI / 1]} scale={[-4.167, 4.167, 4.167]}>
          <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} position={[-0.8, 0.3, 0]} scale={0.0032}>
            <meshStandardMaterial color="#ffffff" roughness={0.4} transparent={false} opacity={1} />
          </mesh>
        </group>
      </group>
    </Float>
  );
};

useGLTF.preload('./models/github.glb');

export default GithubLogo;
