/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { Float, useGLTF } from '@react-three/drei';

/**
 * Renders the MySQL Logo with floating animation and custom colors for its two main parts.
 * @param {string} dolphinColor The hex color code for the dolphin mesh (Cube019). Defaults to '#00758F'.
 * @param {string} baseColor The hex color code for the base mesh (Curve010). Defaults to '#00A2FF'.
 * @param {object} props Other props passed to the Float component.
 */
const MysqlLogo = ({ dolphinColor = '#ffffffff', baseColor = '#00A2FF', ...props }) => {
  const { nodes, materials } = useGLTF('models/mysql.glb');

  return (
    <Float floatIntensity={0.2}>
      <group position={[8, 8, 0]} scale={0.9} {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          rotation={[Math.PI, 0.5, Math.PI]}
          position={[12, -5, 0.0]}>
          <meshStandardMaterial color={baseColor} roughness={0.3} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve010.geometry}
          position={[12, -5, 0.095]}
          rotation={[Math.PI / 2, 0, 0.5]}
          scale={[18.689, 13.456, 18.689]}>
          <meshStandardMaterial color={dolphinColor} roughness={0.3} />
        </mesh>
      </group>
    </Float>
  );
};

useGLTF.preload('models/mysql.glb');

export default MysqlLogo;
