/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { Float, useGLTF } from '@react-three/drei';

const PythonLogo = (props) => {
  const { nodes, materials } = useGLTF('./models/python.glb');
  return (
    <Float {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.D.geometry}
        material={materials.orange}
        position={[-9.23, -1.8, 0]}
        rotation={[-Math.PI / 2, 0, Math.PI + 0.7]}
        scale={1.1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Top_snake.geometry}
        material={materials.blue}
        position={[-9.208, -2.079, 0]}
        rotation={[Math.PI / 2, 0, -0.7]}
        scale={1.1}
      />
    </Float>
  );
};

useGLTF.preload('./models/python.glb');

export default PythonLogo;
