/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AntonioModer (https://sketchfab.com/AntonioModer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unity-logo-3d-mesh-2afd04b26ca64c6b8392f75e217ffdb9
Title: Unity logo 3D mesh
*/

import React, { useRef } from 'react';
import { Float, useGLTF } from '@react-three/drei';

const UnityLogo = (props) => {
  const { nodes, materials } = useGLTF('./models/unityLogo.glb');
  return (
    <Float floatIntensity={1}>
      <group position={[8, 8, 0]} scale={3} {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Unity_3DLogo_Material_0.geometry}
          material={materials.Material}
          position={[3, -0.4, 0.181]}
          rotation={[-Math.PI / 2.2, 0, -1]}
          scale={0.16}
        />
      </group>
    </Float>
  );
};

useGLTF.preload('./models/unityLogo.glb');

export default UnityLogo;
